server:
  port: 8080

spring:
  application:
    name: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #配置Redis数据
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # host主机，默认为localhost
    host: 127.0.0.1
    # 端口号,默认为6379
    port: 6379
    # 密码，默认为空
    password:
    # 连接池
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接超时时间（毫秒）
    timeout: 500

  thymeleaf:
    servlet:
      content-type: text/html

mybatis:
  # 配置Mapper扫描路径
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.miao.test.pojo
